image: node:11

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email 'ci@gitlab'
    - git config --global user.name 'GitLab'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

stages:
    - development_deploy
    - production_deploy

development_deploy:
    only:
        - develop
    environment:
        name: development
    stage: development_deploy
    script:
        - git checkout develop
        - git remote add fortrabbit vacaymenowdev@deploy.us1.frbit.com:vacaymenowdev.git
        - git push fortrabbit develop:master

production_deploy:
    only:
        - master
    environment:
        name: production
    stage: production_deploy
    script:
        - git checkout master
        - git remote add fortrabbit vacaymenow@deploy.us1.frbit.com:vacaymenow.git
        - git push fortrabbit master
